### ISSUE TITLE
builder user change should not cause reboot

### ISSUE THREAD

**Issue by ikke-t** [myllynen/rhel-image#1]
I tried running this on my laptop and was surpriced it waned reboot. That was due creating dummy user. That should not cause reboot. Probably none of these really:

```
builder_packages is changed or
        package_update is changed or
        builder_socket is changed or
        builder_user is changed
```

perhaps just moving (re)start of ```osbuild-composer.socket osbuild-composer.service osbuild-local-worker.socket``` to handler if install/update event happened.

**Comment by myllynen** [comment]
It's a bit excessive, yes, and strictly speaking not necessary but the aim was to go with maximum reproducibility and ensure everything behaves the same even after an eventual reboot. Rebooting would really be necessary only after applying certain updates but since the initial setup is one-time operation it seems easier and should be fine just to reboot if anything changes. Thanks.
